---
title: "README"
author: "ddd"
date: "January 6, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## cmpprocess

cmpprocess is a toolkit for flexible modeling of count processes where data (over- or under-) dispersion exists.

Estimations can be obtained under two data constructs where one has:

(1) data on number of events in an s-unit time interval, or

(2) only wait-time data

To use cmpprocess, one will first need to install the following two packages: 

```R
  install.packages("compoisson")
  install.packages("numDeriv")
````

One can install the latest released version of cmpprocess from CRAN with:

```R
  install.packages("cmpprocess")
````

## Using cmpprocess

To get started with cmpprocess right away, read the notes below. For a more detailed and technical description of COMPoisson processes, see [Zhu et al. (2016)](http://amstat.tandfonline.com/doi/full/10.1080/00031305.2016.1234976).

The cmpprocess package houses four data sets (two phenomena each with a count and waiting time variant)

* floodcount, floodwait (Brillinger , 1995; Guttorp , 1995)

* fetalcount, fetalwait (Guttorp , 1995)

For illustrative purposes, the CMPProcess codes are applied to analyze the Rio Negro flood data set:

```R
  data(floodcount)
````

Note that the key data structures for the CMPProcess codes are vectors (or any ordered sequence) of counts or wait times. These structures will be called in each of the following examples.
  
```R

# Method 1
CMPProcess(floodcount$Counts)

# Method 2
## Assume the analyst knows the dispersion from the count data
CMPProcessWT(.8 , mean(floodwait$WT))

# Method 3
## Should the need arise, an alternative to method 1 is to aggregate the data to a less granular time interval
CMPProcess(bin_size, s=3)

````
